Microverse Project Enumerable Functions
digitekh2i/ruby-enumerables pull request #1
Opened 2020-10-27 21:59 UTC by Janluc

## Enumerable Functions

- Custom versions of the standard Ruby Enumerable Functions
- Use of Yield as well as conditionals in order to receive desired output

2020-10-27 23:25 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @Janluc and @digitekh2i  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your project is passing almost test-cases, congratulations on the good work you have done so far.

### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes]
- [ ] Fix the `instance_of` method, I commented inline your codes, check them and fix it, it is causing your codes to fail running
- [ ] Your codes aren't passing some test cases, read below to understand what I mean:
```bash
# I tested your codes using the following values: 

  ARRAY_SIZE = 100
  LOWEST_VALUE = 0
  HIGHEST_VALUE = 9
  let(:array) { Array.new(ARRAY_SIZE) { rand(LOWEST_VALUE...HIGHEST_VALUE) } }
  let(:block) { proc { |num| num < (LOWEST_VALUE + HIGHEST_VALUE) / 2 } }
  let(:words) { %w[dog door rod blade] }
  let(:range) { Range.new(5, 50) }
  let(:hash) { { a: 1, b: 2, c: 3, d: 4, e: 5 } }
  let(:numbers) { [1, 2i, 3.14] }
  let!(:array_clone) { array.clone }

  # I ran 79 tests
  # => 25 test cases failed, see the failing cases in the comments i added in your codes
```
- [ ] Implement all test cases I added as inline comments in your codes, those are the failing test-cases

If anything seems to be unclear to you, don't hesitate to contact me for more clarification slack: `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-10-27 23:25 UTC, descholar-ceo commented on README.md
> +- etc
Please remove this `etc` it is not meaningful

2020-10-27 23:25 UTC, descholar-ceo commented on README.md
> +This project is [MIT](lic.url) licensed.
This link is not working, fix it please or remove it

2020-10-27 23:25 UTC, descholar-ceo commented on main.rb
> +      if instance_of(Hash) || instance_of?(Range)
The method is `instanceof?` (with question mark)

2020-10-27 23:25 UTC, descholar-ceo commented on README.md
> +👤 **Author1**
Add real names instead of `Author 1`

2020-10-27 23:25 UTC, descholar-ceo commented on README.md
> +👤 **Author2**
Add real names instead of `Author 2`

2020-10-27 23:25 UTC, descholar-ceo commented on README.md
> +Feel free to check the [issues page](issues/).
Add a real issue link here, this one is not working

2020-10-27 23:25 UTC, descholar-ceo commented on main.rb
> +end
#### my_select
- [ ] 7. #my_select returns an enumerator if no block is given

2020-10-27 23:25 UTC, descholar-ceo commented on main.rb
> +  end
#### my_each
- [ ] 1. #my_each returns an Enumerator if no block is given
- [ ] 2. #my_each when a block is given when self is an array returns the array itself after calling the given block once for each element in self
- [ ] 3. #my_each when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- [ ] 4. #my_each_with_index returns an enumerator if no block is given
- [ ] 5. #my_each_with_index when a block is given when self is an array returns the array itself after calling the given block once for each element in self
- [ ] 6. #my_each_with_index when a block is given when self is a range returns the range itself after calling the given block once for each element in self

2020-10-27 23:25 UTC, descholar-ceo commented on main.rb
> +  end
#### my_all?
- [ ] 8. #my_all? when no block or argument is given returns false when one of the collection members are false or nil
- [ ] 9. #my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] 10. #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2020-10-27 23:25 UTC, descholar-ceo commented on main.rb
> +  end
#### my_any?
- [ ] 11. #my_any? when no block or argument is given returns false if at least one of the collection is not true
- [ ] 12. #my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex
- [ ] 13. #my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] 14. #my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2020-10-27 23:25 UTC, descholar-ceo commented on main.rb
> +  end
#### my_none?
- [ ] 15. #my_none? when no block or argument is given returns true only if none of the collection members is true
- [ ] 16. #my_none? when a Regex is passed as an argument returns true if none of the collection matches the Regex
- [ ] 17. #my_none? when a Regex is passed as an argument returns false if any of the collection matches the Regex
- [ ] 18. #my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- [ ] 19. #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern

2020-10-27 23:25 UTC, descholar-ceo commented on main.rb
> +  end
#### my_inject
- [ ] 25. #my_inject raises a "LocalJumpError" when no block or argument is given

2020-10-27 23:25 UTC, descholar-ceo commented on main.rb
> +  end
#### my_map
- [ ] 20. #my_map returns a new array with the results of running a given block once for every element in enum.
- [ ] 21. #my_map returns a new array with the results of running a given block once for every element in enum::range
- [ ] 22. #my_map returns an Enumerator if no block is given
- [ ] 23. #my_map accepts a proc as an argument and returns a new array with the results of running the proc once for every element in enum.
- [ ] 24. #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

2020-10-28 15:35 UTC, mahmoud717 requested changes
## Changes Requested #
- please go back and make the changes requested by the first tse
 do all of the changes requested for (my_each, my_all, my_any?, my_select?, my_none? , and my_map)

2020-10-28 16:09 UTC, Janluc commented
> ## Changes Requested
> * please go back and make the changes requested by the first tse
>   do all of the changes requested for (my_each, my_all, my_any?, my_select?, my_none? , and my_map)

Hey thanks for the review! However, all the changes request by the TSE are provided in this code. The test cases to go along with the changes are also in the live demo link.

2020-10-28 20:06 UTC, Georjane approved these changes
# Status: PR Approved ✔️
## Hi @Janluc and @digitekh2i

Great job on your enumerable methods. 👏
They all have the same behavior like the normal enumerable methods. You can go ahead and merge this PR.

Goodluck on your next project 👍

2020-10-28 20:35 UTC, merged